### ISSUE TITLE
CrossVersionObjectReference missing `kind` field

### ISSUE THREAD

**Issue by shalseban** [zbrookle/avionix#64]
I am trying to deploy an HPA which uses `CrossVersionObjectReference`. I do not see the `kind` field in the api docs [here](https://avionix.readthedocs.io/en/latest/reference/kubernetes/modules/avionix.kube.autoscaling.html#avionix.kube.autoscaling.CrossVersionObjectReference). Let me know if I am missing something.

**Comment by zbrookle** [comment]
@shalseban You're right, that is missing, I can add it
