### ISSUE TITLE
Is there a way to create Deployment type Job, please add some example for Job

### ISSUE THREAD

**Issue by arun2sasi** [zbrookle/avionix#72]
I need to run a  job in AKS, was looking for an option to deploy Job using avionix lib, pls add some example

**Comment by zbrookle** [comment]
@arun2sasi Here's the reference to that type in the docs https://avionix.readthedocs.io/en/latest/reference/kubernetes/modules/avionix.kube.batch.html?highlight=Job#avionix.kube.batch.Job
