### ISSUE TITLE
output_directory in chart builder is ignored

### ISSUE THREAD

**Issue by Bob10918** [zbrookle/avionix#76]
Hi,
changing the output directory in chart builder lead to unwanted behaviors, indeed it is considered only when writing out new chart files, not when deleting them after installation:
```    
def __delete_chart_directory(self):
    if os.path.exists(self.chart_info.name):
        shutil.rmtree(self.chart_info.name)
```
(chart_info.name doesn't include the set output_directory).
Especially during upgrades, this cause merging values from old installations, differently from the expected program behavior.
I think the fix is really easy to implement (I also noticed there is a pretty old issue request to resolve this bug).
Please let me know if you prefer I fix this in a new merge request.

**Comment by zbrookle** [comment]
Hey thanks for bringing this up I just merged the request that should fix it
